### PR TITLE
Some QoL improvements

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Delete unnecessary files that don't need to be in the repo. The .idea files usually just dirty up commits and make them harder to read, and they are auto-generated whenever someone opens the project with Android Studio anyway.

### 2nd commit
- Update gradle wrapper to 6.8.3 using git bash.

### 3rd commit
- Replace submodule with a jitpack implementation, so no more of that stupid garbage findbugs error and garbage workaround.

### 4th commit
- Update Android Studio 3.3.2 -> 4.1.3
- Update Gson 2.8.5 -> 2.8.6 ([changelog](https://github.com/google/gson/blob/master/CHANGELOG.md))
- Exclude META-INF from packaging to cut down on APK size (ACRA still works)

### 5th commit
- Use SwitchPreferenceCompat so that devices under Lollipop get the Material design switches instead of the old Holo switches

### 6th commit
- Replace android platform icons with vector drawables

### CODE REVIEW

**Comment by felixwiemuth** [comment]
Hi @TacoTheDank, thanks for your interest and effort. Normally I would prefer discussing things first to avoid duplicate or unnecessary work, but there seem to be some useful improvements and I'll take a look. You'll just have to bear with some questions and comments. :)

**Comment by TacoTheDank** [comment]
@felixwiemuth Sounds good to me, thanks :)

**Comment by felixwiemuth** [comment]
I have now reviewed your suggestions, so here are some comments and questions.

> ### 1st commit
> 
>   * Delete unnecessary files that don't need to be in the repo. The .idea files usually just dirty up commits and make them harder to read, and they are auto-generated whenever someone opens the project with Android Studio anyway.
> 
There is some project configuration that should be in the repo (like code style, license etc.). The project specific things are of course not generated when opening Android Studio. It would of course be better if this configuration was IDE-independent, but I'm not sure in how far this is possible/practicable for everything. There is a discussion about this topic on [Stackoverflow](https://stackoverflow.com/questions/26336709/android-studio-should-the-entire-idea-directory-be-in-git-ignore).

Android Studio already creates .gitignore entries for some files and directories in .idea when creating a new project (see [Stackoverflow](https://stackoverflow.com/questions/16736856/what-should-be-in-my-gitignore-for-an-android-studio-project)) and adds the rest to git, so that should somewhat represent the default of what should be under version control.

I don't see any problems with the current files, but if there is anything that should be updated/changed for a good reason, let me know. Also, changes to these files shouldn't dirty up git commits because they should be done in separate commits ;).

> 
> ### 2nd commit
> 
>   * Update gradle wrapper to 6.8.3 using git bash.
> 
The reason I did not update gradle yet were problems with the submodule (where gradle would have to be upgraded as well and that turned out to be more complicated). But apparently replacing the submodule with a different kind of dependency allowed you to update gradle without problems? That is good to know. But maybe there is also a way keeping the submodule (without updating it)?

> 
> ### 3rd commit
> 
>   * Replace submodule with a jitpack implementation, so no more of that stupid garbage findbugs error and garbage workaround.
> 
Thanks for pointing out JitPack, it seems to be an interesting project. However, I also see some disadvantages:
- You have to trust another service to build the library correctly.
- When you want to locally develop and test the library together with the app, it is much easier to have it as a submodule. Temporarily replacing the JitPack dependency with a submodule dependency is probably not very convenient either.

So I think this is currently not the right option and the submodule is more suitable. It should be cleaned up anyway (and maybe updated from upstream) and then it will also be possible to upgrade gradle this way.

> 
> ### 4th commit
> 
>   * Update Android Studio 3.3.2 -> 4.1.3
> 
I'll upgrade Android build tools when updating gradle.

>
>   * Update Gson 2.8.5 -> 2.8.6 ([changelog](https://github.com/google/gson/blob/master/CHANGELOG.md))
> 
Thanks for the hint. I'm regularly updating libraries when Android Studio shows that there is a new version (when looking at `build.gradle`) but somehow for this Gson update it did not show it (even though apparently the update was already released in 2019). It first showed that there is an update after manually updating and then reverting it.

>
>   * Exclude META-INF from packaging to cut down on APK size (ACRA still works)
>
Surely there is a reason for having the META-INF if it is there by default. As I understand, it also contains the signatures, so probably also the F-Droid signatures will be there, which one of course wants to keep. Regarding APK size, META-INF with only 150KB uncompressed (v0.9.6) shouldn't matter.

> 
> ### 5th commit
> 
>   * Use SwitchPreferenceCompat so that devices under Lollipop get the Material design switches instead of the old Holo switches
> 
Thanks for the hint, this makes sense. You can make a new pull request for this (towards develop).

> 
> ### 6th commit
> 
>   * Replace android platform icons with vector drawables
>
Can you explain what the purpose of this is (e.g. save space, better quality)? Where do the vector images come from? I think in general it is preferable to use the icons provided by the platform, or, if needed, by a library.

---

Overall thanks for some useful hints which I will incorporate or remember for later. I won't merge this PR as for most things it makes more sense if I do them directly in accordance with other changes. But as said, you can make a separate PR for the No. 5 changes :).

**Comment by TacoTheDank** [comment]
> > * Replace submodule with a jitpack implementation, so no more of that stupid garbage findbugs error and garbage workaround.
> 
> Thanks for pointing out JitPack, it seems to be an interesting project. However, I also see some disadvantages:
> 
> * You have to trust another service to build the library correctly.
> * When you want to locally develop and test the library together with the app, it is much easier to have it as a submodule. Temporarily replacing the JitPack dependency with a submodule dependency is probably not very convenient either.
> 
> So I think this is currently not the right option and the submodule is more suitable. It should be cleaned up anyway (and maybe updated from upstream) and then it will also be possible to upgrade gradle this way.

Oh yes, please update that library from the upstream! :) Actually, as a matter of fact, you may not even need to use this library anymore, as a new feature that could be used instead has been added with RecyclerView 1.2.0: [ConcatAdapter](https://developer.android.com/jetpack/androidx/releases/recyclerview#recyclerview-1.2.0)

> > * Exclude META-INF from packaging to cut down on APK size (ACRA still works)
> 
> Surely there is a reason for having the META-INF if it is there by default. As I understand, it also contains the signatures, so probably also the F-Droid signatures will be there, which one of course wants to keep. Regarding APK size, META-INF with only 150KB uncompressed (v0.9.6) shouldn't matter.

Excluding META-INF does not exclude signatures, but I mean ok, if you want to keep it then that's fine too :P

> > ### 5th commit
> > 
> > * Use SwitchPreferenceCompat so that devices under Lollipop get the Material design switches instead of the old Holo switches
> 
> Thanks for the hint, this makes sense. You can make a new pull request for this (towards develop).

Will do.

> > ### 6th commit
> > 
> > * Replace android platform icons with vector drawables
> 
> Can you explain what the purpose of this is (e.g. save space, better quality)? Where do the vector images come from? I think in general it is preferable to use the icons provided by the platform, or, if needed, by a library.

They come from here https://fonts.google.com/icons?selected=Material+Icons. The platform icon resources are remnants from the single digit API days (as far as I can tell). They should not be used because they look very bad and out-of-place on pretty much any device above API 19. The vector images are generated using the built-in Asset Studio:

image

**Comment by felixwiemuth** [comment]
> Oh yes, please update that library from the upstream! :) Actually, as a matter of fact, you may not even need to use this library anymore, as a new feature that could target this use case has been added with RecyclerView 1.2.0: [ConcatAdapter](https://developer.android.com/jetpack/androidx/releases/recyclerview#recyclerview-1.2.0)

Thanks for the hint, this makes things a lot easier, and you found it just in time! :tada:
I was about to start on the maintenance/upgrading stuff soon, and with the `ConcatAdapter` just released in time, I probably can save quite a bit of work. Reading the blog post, I'm quite positive the SectionedRecyclerView library is not needed anymore and the structure that's used for the reminders list should be quite easily realizable with `ConcatAdapter`.

**Comment by TacoTheDank** [comment]
Glad I could help!

**Pull request closed without merging**
